<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminMain.aspx.cs" Inherits="AdminMain" %>

<!DOCTYPE html>



<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        Succesfully logged in as admin
    </div>

        <asp:Menu ID="Menu1" runat="server" OnMenuItemClick="Menu1_MenuItemClick" Orientation="Horizontal">
            <Items>
                <asp:MenuItem Text="Log work" Value="0"></asp:MenuItem>
                <asp:MenuItem Text="Manage users" Value="1"></asp:MenuItem>
                <asp:MenuItem Selected="True" Text="Manage projects" Value="2"></asp:MenuItem>
            </Items>
        </asp:Menu>
        <asp:MultiView ID="multiTabs" runat="server" ActiveViewIndex="0">

               
                
              <br />
              <br />
          <asp:View ID="ViewPontaje" runat="server">
                <br />
               
            <asp:GridView ID="GridViewPontaje" CssClass="Grid" runat="server" AutoGenerateColumns="false"  PageSize="10" AllowPaging="true" DataSourceID="dsLogs" OnRowCommand="GridView_Logs">
                <EmptyDataRowStyle CssClass="EmptyData" />
                <EmptyDataTemplate>

<div>

No Data Available

</div>
                    <script>
                        $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                        </script>

</EmptyDataTemplate>
            <Columns>
                 <asp:BoundField DataField="name" HeaderText="Name" />
                 <asp:BoundField DataField="description" HeaderText="Description" />

                 <asp:TemplateField ShowHeader="False">
                     <ItemTemplate>
                         <asp:Button ID="ButtonStart" runat="server" CommandArgument='<%# Eval("id") %>' CommandName="Start" Text="Start working"></asp:Button>
                     </ItemTemplate>
                 </asp:TemplateField>

                <asp:TemplateField ShowHeader="False">
                    <ItemTemplate>
                        <asp:Button ID="ButtonStop" runat="server" CommandArgument='<%# Eval("id") %>' CommandName="Stop" Text="Stop working" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            
            </asp:GridView>

            <asp:ObjectDataSource ID="dsLogs" runat="server" EnablePaging="true" SelectMethod="GetProjects"
                 SelectCountMethod="GetProjectsCount" TypeName="Projects" MaximumRowsParameterName="maxRows"
                 StartRowIndexParameterName="startIndex">
            </asp:ObjectDataSource>

          </asp:View>

            
           <asp:View ID="ViewUsers" runat="server">
            

             <br />

               <asp:GridView ID="GridViewUsers" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id" DataSourceID="SqlDataSourceUsers">
                   <Columns>
                      
                       <asp:BoundField DataField="first_name" HeaderText="first_name" SortExpression="first_name" />
                       <asp:BoundField DataField="last_name" HeaderText="last_name" SortExpression="last_name" />
                       <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                       <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                       <asp:TemplateField ItemStyle-CssClass="TemplateFieldOneColumn" HeaderText="role">
                        <ItemTemplate>
                             <asp:Label runat="server" Text='<% #GetLabelText(Eval("id_role")) %>' />
                        </ItemTemplate>
                        </asp:TemplateField>
                      
                   </Columns>
               </asp:GridView>
                <br />
                 <br />
               <asp:Label ID="LabelUsername" runat="server" Text="Username"></asp:Label>
               <asp:TextBox ID="TextBoxUsername" runat="server"></asp:TextBox>
               <asp:Button ID="ButtonGrantAdminRights" runat="server" OnClick="ButtonGrantAdminRights_Click" Text="Grant Admin Rights" />
               <asp:Button ID="ButtonRevokeAdminRights" runat="server" OnClick="ButtonRevokeAdminRights_Click" Text="Revoke Admin Rights" />
               <asp:SqlDataSource ID="SqlDataSourceUsers" runat="server" ConnectionString="<%$ ConnectionStrings:Pontaje_v2ConnectionString %>" SelectCommand="SELECT * FROM [Users]"
                  DeleteCommand="delete from [Users] where [id]=@id" >

               

               </asp:SqlDataSource>
               </asp:View>

              
          

            
            <asp:View ID="ViewProjects" runat="server">
                 <br />
                 
                
                  
   

                 <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server"  >
            <ContentTemplate>
                   
                 <asp:GridView ID="GridViewProjects" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" >
                     

                     <EmptyDataRowStyle CssClass="EmptyData" />
                                <EmptyDataTemplate>

                                <div>

                                    No Data Available

                    </div>
                                     <script>
                        $(".EmptyData").parents("table").css("border-width", "0px").prop("border", "0");
                        </script>

                        </EmptyDataTemplate>
                    
                     <Columns>
                        
                         <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                         <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                     </Columns>
                 </asp:GridView>
                 <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Pontaje_v2ConnectionString %>" SelectCommand="SELECT * FROM [Projects]"
                     UpdateCommand="Update [Projects] set [name]=@name, [description]=@description where [id]=@id" DeleteCommand="delete from [Projects] where [id]=@id">

                 </asp:SqlDataSource>

                
                 <br />
                 <br />
                 <br />

                <form id="formAddProject"> 
      
                     
                               
        <asp:Label ID="LabelName" runat="server" Text="Name" Width="100px"></asp:Label>
        <asp:TextBox ID="TextBoxName" runat="server"></asp:TextBox>
        <p>
            <asp:Label ID="LabelDescription" runat="server" Text="Description"  Width="100px"></asp:Label>
            <asp:TextBox ID="TextBoxDescription" runat="server" TextMode="MultiLine" Height="63px" Width="439px"></asp:TextBox>
        </p>
                    
                <asp:Button ID="ButtonSave" runat="server" Text="Add new project" Enabled="True" Width="165px" OnClick="ButtonSave_Click" />
        <asp:Button ID="ButtonCancel" runat="server" Text="Clear" Width="165px" OnClick="ButtonCancel_Click"  />
            </ContentTemplate>
            <Triggers >
                
    <asp:PostBackTrigger ControlID="ButtonSave"  />
    <asp:PostBackTrigger ControlID="ButtonCancel"  />
</Triggers>
        </asp:UpdatePanel>

                </asp:View>
             


        </asp:MultiView>
        <p>
            <asp:Button ID="ButtonLogout" runat="server" OnClick="ButtonLogout_Click" Text="Logout" />
        </p>
       
    </form>
</body>
</html>


