<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminMain.aspx.cs" Inherits="AdminMain" %>

<!DOCTYPE html>



<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        Succesfully logged in as admin
    </div>

        <asp:Menu ID="Menu1" runat="server" OnMenuItemClick="Menu1_MenuItemClick" Orientation="Horizontal">
            <Items>
                <asp:MenuItem Text="Log work" Value="0"></asp:MenuItem>
                <asp:MenuItem Text="Manage users" Value="1"></asp:MenuItem>
                <asp:MenuItem Selected="True" Text="Manage projects" Value="2"></asp:MenuItem>
            </Items>
        </asp:Menu>
        <asp:MultiView ID="multiTabs" runat="server" ActiveViewIndex="0">
              <br />
              <br />
          <asp:View ID="ViewPontaje" runat="server">
                <br />
                
            <asp:GridView ID="gvProjects" CssClass="Grid" runat="server" AutoGenerateColumns="false"  PageSize="10" AllowPaging="true" DataSourceID="dsLogs" OnRowCommand="GridView_Logs">
            <Columns>
                 <asp:BoundField DataField="name" HeaderText="Name" />
                 <asp:BoundField DataField="description" HeaderText="Description" />

                 <asp:TemplateField ShowHeader="False">
                    <ItemTemplate>
                        <asp:Button ID="ButtonStart" runat="server" CommandName="Start"  CommandArgument='<%# Eval("id") %>'  Text="Start working" ></asp:Button>
                    </ItemTemplate>
                 </asp:TemplateField>

                <asp:TemplateField ShowHeader="False">
                    <ItemTemplate>
                        <asp:Button ID="ButtonStop" runat="server" CommandName="Stop"  CommandArgument='<%# Eval("id") %>'  Text="Stop working" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            
            </asp:GridView>

            <asp:ObjectDataSource ID="dsLogs" runat="server" EnablePaging="true" SelectMethod="GetProjects"
                 SelectCountMethod="GetProjectsCount" TypeName="Projects" MaximumRowsParameterName="maxRows"
                 StartRowIndexParameterName="startIndex">
            </asp:ObjectDataSource>
          </asp:View>

            
           <asp:View ID="ViewUsers" runat="server">
            

             <br />

               <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id" DataSourceID="SqlDataSource2">
                   <Columns>
                      
                       <asp:BoundField DataField="first_name" HeaderText="first_name" SortExpression="first_name" />
                       <asp:BoundField DataField="last_name" HeaderText="last_name" SortExpression="last_name" />
                       <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                       <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                      
                   </Columns>
               </asp:GridView>
               <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:Pontaje_v2ConnectionString %>" SelectCommand="SELECT * FROM [Users]"
                  DeleteCommand="delete from [Users] where [id]=@id" >

               </asp:SqlDataSource>
               </asp:View>

              
          

            
            <asp:View ID="ViewProjects" runat="server">
                 <br />
                 <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1">
                     <Columns>
                        
                         <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                         <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                     </Columns>
                 </asp:GridView>
                 <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Pontaje_v2ConnectionString %>" SelectCommand="SELECT * FROM [Projects]"
                     UpdateCommand="Update [Projects] set [name]=@name, [description]=@description where [id]=@id" DeleteCommand="delete from [Projects] where [id]=@id">

                 </asp:SqlDataSource>

                
                 <br />
                 <br />
                 <br />

                <form id="formAddProject"> 
      
                     
                               
        <asp:Label ID="LabelName" runat="server" Text="Name" Width="100px"></asp:Label>
        <asp:TextBox ID="TextBoxName" runat="server"></asp:TextBox>
        <p>
            <asp:Label ID="LabelDescription" runat="server" Text="Description"  Width="100px"></asp:Label>
            <asp:TextBox ID="TextBoxDescription" runat="server" TextMode="MultiLine" Height="63px" Width="439px"></asp:TextBox>
        </p>
        <p>
            &nbsp;</p>
        <p>
            &nbsp;</p>
                <asp:Button ID="ButtonSave" runat="server" Text="Add new project" Width="165px" OnClick="ButtonSave_Click" />
        <asp:Button ID="ButtonCancel" runat="server" Text="Clear" Width="169px" OnClick="ButtonCancel_Click" style="margin-bottom: 0px" />
              
       
     </form> 
                    

          </asp:View>
               
             

                       


        </asp:MultiView>

       
    </form>
</body>
</html>
